### ISSUE TITLE
Beta / Release checklist

### ISSUE THREAD

**Issue by minasmart** [Shopify/js-buy-sdk#406]
As part of moving toward release, it's time normalize how we work with graphql, standardize our method names, and clean up some of the old stuff. Items may be added to this list.

- [x] Convert to static queries. #405 
- [x] Strip out meaningless tests. #410
- [x] Normalize method names by resource. #412 
- [x] Simplify build to reflect conventional rollup semantics. #420
- [x] Update migration guide. #415
- [x] Update docs. #414 
- [ ] Update examples.
- [ ] Update doc site.

**Comment by andrevvm** [comment]
Apologies if this isn't the correct place, but I have a question regarding timeline on v1.0

When is v1.0 expected to be released publicly, and will v0.x continue to function for long after the release? I have a project that is almost finished built on v0.x and wondering if it is safe to launch publicly, and upgrade to v1.0 at a later stage.

**Comment by minasmart** [comment]
`v0` will not be deprecated, but the APIs it's connected to will remain active for quite some time. We have no timelines on turning those off for now, so you're safe. If we ever worked in that direction, you would receive a notice through your partner account and there would be  a lot of runway.

That said, `v1` should be fully released in the next couple of weeks.

**Comment by rebeccajfriedman** [comment]
Closing due to inactivity.
